<?php

namespace Proxies\__CG__\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EOrdine extends \Entity\EOrdine implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'id', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'note', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'dataEsecuzione', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'dataRicezione', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'dataConsegna', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'costo', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'cliente', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'itemOrdini', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'segnalazione', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'stato', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'indirizzoConsegna', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'metodoPagamento'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'id', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'note', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'dataEsecuzione', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'dataRicezione', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'dataConsegna', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'costo', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'cliente', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'itemOrdini', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'segnalazione', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'stato', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'indirizzoConsegna', '' . "\0" . 'Entity\\EOrdine' . "\0" . 'metodoPagamento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EOrdine $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataEsecuzione()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataEsecuzione', []);

        return parent::getDataEsecuzione();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataRicezione()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataRicezione', []);

        return parent::getDataRicezione();
    }

    /**
     * {@inheritDoc}
     */
    public function getCosto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCosto', []);

        return parent::getCosto();
    }

    /**
     * {@inheritDoc}
     */
    public function getStato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStato', []);

        return parent::getStato();
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente(): \Entity\ECliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function getItemOrdini()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemOrdini', []);

        return parent::getItemOrdini();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndirizzoConsegna(): \Entity\EIndirizzo
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndirizzoConsegna', []);

        return parent::getIndirizzoConsegna();
    }

    /**
     * {@inheritDoc}
     */
    public function getMetodoPagamento(): \Entity\ECarta_credito
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetodoPagamento', []);

        return parent::getMetodoPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getDataConsegna(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataConsegna', []);

        return parent::getDataConsegna();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataEsecuzione($dataEsecuzione): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataEsecuzione', [$dataEsecuzione]);

        return parent::setDataEsecuzione($dataEsecuzione);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataRicezione($dataRicezione): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataRicezione', [$dataRicezione]);

        return parent::setDataRicezione($dataRicezione);
    }

    /**
     * {@inheritDoc}
     */
    public function setDataConsegna($dataConsegna): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataConsegna', [$dataConsegna]);

        return parent::setDataConsegna($dataConsegna);
    }

    /**
     * {@inheritDoc}
     */
    public function setCosto($costo): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCosto', [$costo]);

        return parent::setCosto($costo);
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente($cliente): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function setStato($stato): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStato', [$stato]);

        return parent::setStato($stato);
    }

    /**
     * {@inheritDoc}
     */
    public function setIndirizzoConsegna(\Entity\EIndirizzo $indirizzo): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndirizzoConsegna', [$indirizzo]);

        return parent::setIndirizzoConsegna($indirizzo);
    }

    /**
     * {@inheritDoc}
     */
    public function setMetodoPagamento(\Entity\ECarta_credito $carta): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetodoPagamento', [$carta]);

        return parent::setMetodoPagamento($carta);
    }

    /**
     * {@inheritDoc}
     */
    public function addItemOrdine(\Entity\EItemOrdine $item): \Entity\EOrdine
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItemOrdine', [$item]);

        return parent::addItemOrdine($item);
    }

    /**
     * {@inheritDoc}
     */
    public function hasWarning(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasWarning', []);

        return parent::hasWarning();
    }

}
