<?php

namespace Proxies\__CG__\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ECliente extends \Entity\ECliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entity\\ECliente' . "\0" . 'metodiPagamento', '' . "\0" . 'Entity\\ECliente' . "\0" . 'indirizziConsegna', '' . "\0" . 'Entity\\ECliente' . "\0" . 'ordini', '' . "\0" . 'Entity\\ECliente' . "\0" . 'segnalazioni'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entity\\ECliente' . "\0" . 'metodiPagamento', '' . "\0" . 'Entity\\ECliente' . "\0" . 'indirizziConsegna', '' . "\0" . 'Entity\\ECliente' . "\0" . 'ordini', '' . "\0" . 'Entity\\ECliente' . "\0" . 'segnalazioni'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ECliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMetodiPagamento(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetodiPagamento', []);

        return parent::getMetodiPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function getIndirizziConsegna(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndirizziConsegna', []);

        return parent::getIndirizziConsegna();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdini(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdini', []);

        return parent::getOrdini();
    }

    /**
     * {@inheritDoc}
     */
    public function getSegnalazioni(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSegnalazioni', []);

        return parent::getSegnalazioni();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetodiPagamento($metodiPagamento): \Entity\ECliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetodiPagamento', [$metodiPagamento]);

        return parent::setMetodiPagamento($metodiPagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function setIndirizziConsegna($indirizziConsegna): \Entity\ECliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndirizziConsegna', [$indirizziConsegna]);

        return parent::setIndirizziConsegna($indirizziConsegna);
    }

    /**
     * {@inheritDoc}
     */
    public function addIndirizzoConsegna(\Entity\EIndirizzo $indirizzo): \Entity\ECliente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIndirizzoConsegna', [$indirizzo]);

        return parent::addIndirizzoConsegna($indirizzo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome(string $nome): \Entity\EUtente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getCognome(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCognome', []);

        return parent::getCognome();
    }

    /**
     * {@inheritDoc}
     */
    public function setCognome(string $cognome): \Entity\EUtente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCognome', [$cognome]);

        return parent::setCognome($cognome);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \Entity\EUtente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \Entity\EUtente
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuolo(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuolo', []);

        return parent::getRuolo();
    }

}
